//
//  Cards.swift
//  JitsuCore
//
//  Created by Tom Knighton on 11/03/2026.
//

public var cards: [Card] {
    return [
        // Set 1
        .init(id: "card_1", element: .fire, level: 3, colour: .blue, artKey: nil),
        .init(id: "card_2", element: .fire, level: 2, colour: .green, artKey: nil),
        .init(id: "card_3", element: .fire, level: 8, colour: .green, artKey: nil),
        .init(id: "card_4", element: .fire, level: 3, colour: .orange, artKey: nil),
        .init(id: "card_5", element: .fire, level: 4, colour: .purple, artKey: nil),
        .init(id: "card_6", element: .fire, level: 6, colour: .purple, artKey: nil),
        .init(id: "card_7", element: .fire, level: 2, colour: .red, artKey: nil),
        .init(id: "card_8", element: .fire, level: 7, colour: .red, artKey: nil),
        .init(id: "card_9", element: .fire, level: 2, colour: .yellow, artKey: nil),
        .init(id: "card_10", element: .fire, level: 5, colour: .yellow, artKey: nil),
        .init(id: "card_11", element: .snow, level: 3, colour: .blue, artKey: nil),
        .init(id: "card_12", element: .snow, level: 2, colour: .green, artKey: nil),
        .init(id: "card_13", element: .snow, level: 5, colour: .green, artKey: nil),
        .init(id: "card_14", element: .snow, level: 3, colour: .orange, artKey: nil),
        .init(id: "card_15", element: .snow, level: 4, colour: .purple, artKey: nil),
        .init(id: "card_16", element: .snow, level: 8, colour: .purple, artKey: nil),
        .init(id: "card_17", element: .snow, level: 2, colour: .red, artKey: nil),
        .init(id: "card_18", element: .snow, level: 6, colour: .red, artKey: nil),
        .init(id: "card_19", element: .snow, level: 2, colour: .yellow, artKey: nil),
        .init(id: "card_20", element: .snow, level: 7, colour: .yellow, artKey: nil),
        .init(id: "card_21", element: .water, level: 3, colour: .blue, artKey: nil),
        .init(id: "card_22", element: .water, level: 5, colour: .blue, artKey: nil),
        .init(id: "card_23", element: .water, level: 2, colour: .green, artKey: nil),
        .init(id: "card_24", element: .water, level: 8, colour: .green, artKey: nil),
        .init(id: "card_25", element: .water, level: 3, colour: .orange, artKey: nil),
        .init(id: "card_26", element: .water, level: 4, colour: .purple, artKey: nil),
        .init(id: "card_27", element: .water, level: 6, colour: .purple, artKey: nil),
        .init(id: "card_28", element: .water, level: 2, colour: .red, artKey: nil),
        .init(id: "card_29", element: .water, level: 7, colour: .red, artKey: nil),
        .init(id: "card_30", element: .water, level: 2, colour: .yellow, artKey: nil),
        .init(id: "card_31", element: .fire, level: 2, colour: .blue, artKey: nil),
        .init(id: "card_32", element: .fire, level: 5, colour: .blue, artKey: nil),
        .init(id: "card_33", element: .fire, level: 4, colour: .green, artKey: nil),
        .init(id: "card_34", element: .fire, level: 6, colour: .orange, artKey: nil),
        .init(id: "card_35", element: .fire, level: 3, colour: .purple, artKey: nil),
        .init(id: "card_36", element: .fire, level: 5, colour: .red, artKey: nil),
        .init(id: "card_37", element: .fire, level: 4, colour: .yellow, artKey: nil),
        .init(id: "card_38", element: .snow, level: 2, colour: .blue, artKey: nil),
        .init(id: "card_39", element: .snow, level: 5, colour: .blue, artKey: nil),
        .init(id: "card_40", element: .snow, level: 4, colour: .green, artKey: nil),
        .init(id: "card_41", element: .snow, level: 6, colour: .orange, artKey: nil),
        .init(id: "card_42", element: .snow, level: 3, colour: .purple, artKey: nil),
        .init(id: "card_43", element: .snow, level: 5, colour: .red, artKey: nil),
        .init(id: "card_44", element: .snow, level: 4, colour: .yellow, artKey: nil),
        .init(id: "card_45", element: .water, level: 2, colour: .blue, artKey: nil),
        .init(id: "card_46", element: .water, level: 4, colour: .green, artKey: nil),
        .init(id: "card_47", element: .water, level: 6, colour: .orange, artKey: nil),
        .init(id: "card_48", element: .water, level: 3, colour: .purple, artKey: nil),
        .init(id: "card_49", element: .water, level: 5, colour: .red, artKey: nil),
        .init(id: "card_50", element: .water, level: 5, colour: .yellow, artKey: nil),
        .init(id: "card_51", element: .fire, level: 6, colour: .blue, artKey: nil),
        .init(id: "card_52", element: .fire, level: 5, colour: .green, artKey: nil),
        .init(id: "card_53", element: .fire, level: 4, colour: .orange, artKey: nil),
        .init(id: "card_54", element: .fire, level: 8, colour: .purple, artKey: nil),
        .init(id: "card_55", element: .fire, level: 3, colour: .red, artKey: nil),
        .init(id: "card_56", element: .fire, level: 7, colour: .yellow, artKey: nil),
        .init(id: "card_57", element: .snow, level: 6, colour: .blue, artKey: nil),
        .init(id: "card_58", element: .snow, level: 7, colour: .green, artKey: nil),
        .init(id: "card_59", element: .snow, level: 4, colour: .orange, artKey: nil),
        .init(id: "card_60", element: .snow, level: 8, colour: .orange, artKey: nil),
        .init(id: "card_61", element: .snow, level: 6, colour: .purple, artKey: nil),
        .init(id: "card_62", element: .snow, level: 3, colour: .red, artKey: nil),
        .init(id: "card_63", element: .snow, level: 5, colour: .yellow, artKey: nil),
        .init(id: "card_64", element: .water, level: 6, colour: .blue, artKey: nil),
        .init(id: "card_65", element: .water, level: 5, colour: .green, artKey: nil),
        .init(id: "card_66", element: .water, level: 4, colour: .orange, artKey: nil),
        .init(id: "card_67", element: .water, level: 8, colour: .purple, artKey: nil),
        .init(id: "card_68", element: .water, level: 3, colour: .red, artKey: nil),
        .init(id: "card_69", element: .water, level: 4, colour: .yellow, artKey: nil),
        .init(id: "card_70", element: .water, level: 47, colour: .yellow, artKey: nil),
    ]
}
